"""второй тест

Revision ID: c4d7b934ab6f
Revises: 3bf6f5e6dc7f
Create Date: 2021-04-11 15:44:41.063516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d7b934ab6f'
down_revision = '3bf6f5e6dc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
